# Generated by Django 5.2 on 2025-04-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainuser',
            name='nonce',
            field=models.CharField(help_text='Random nonce for signature verification. Automatically generated.', max_length=100),
        ),
    ]
