# Generated by Django 5.2 on 2025-04-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_appointment_department_remove_doctor_doj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
